apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rd-caseworker-ref-api 
  description: rd-caseworker-ref-api API
spec:
  type: openapi
  system: rd-caseworker-ref-api
  lifecycle: production
  owner: dcd_group_referencedata_v2
  definition: |
    openapi: 3.0.0
    info:
      description: Api Documentation
      version: "1.0"
      title: Api Documentation
      termsOfService: urn:tos
      contact: {}
      license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0
    tags:
      - name: case-flag-api-controller
        description: Case Flag Api Controller
      - name: crd-api-controller
        description: Crd Api Controller
      - name: root-controller
        description: Root Controller
    paths:
      /:
        get:
          tags:
            - root-controller
          summary: welcome
          operationId: welcomeUsingGET
          responses:
            "200":
              description: OK
              content:
                "*/*":
                  schema:
                    type: string
      "/refdata/commondata/caseflags/service-id={service-id}":
        get:
          tags:
            - case-flag-api-controller
          summary: CommonData API will be used to retrieve the list of case flags for a
            given service id.
          description: "Any valid IDAM role should be able to access this API "
          operationId: retrieveCaseFlagsByServiceIdUsingGET
          parameters:
            - name: flag-type
              in: query
              description: Allowed Values are PARTY or CASE
              required: false
              schema:
                type: string
            - name: service-id
              in: path
              description: Any Valid String is allowed
              required: true
              schema:
                type: string
            - name: welsh-required
              in: query
              description: Allowed Values are Y or N
              required: false
              schema:
                type: string
          responses:
            "200":
              description: Successfully retrieved list of Case Flag for the request provided
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/CaseFlag"
            "400":
              description: Bad Request
            "401":
              description: "Forbidden Error: Access denied"
            "500":
              description: Internal Server Error
          security:
            - Authorization: []
            - ServiceAuthorization: []
      /refdata/commondata/lov/categories:
        get:
          tags:
            - crd-api-controller
          summary: CommonData API will be used to retrieve the list of category values for
            a given category id.
          description: "Any valid IDAM role should be able to access this API "
          operationId: retrieveHearingChannelByCategoryIdUsingGET
          parameters:
            - name: category-id
              in: path
              description: Any Valid String is allowed
              required: true
              schema:
                type: string
            - name: parent-category
              in: query
              description: Any Valid String is allowed
              required: false
              schema:
                type: string
            - name: parent-key
              in: query
              description: Any Valid String is allowed
              required: false
              schema:
                type: string
            - name: service-id
              in: query
              description: Any Valid String is allowed
              required: false
              schema:
                type: string
          responses:
            "200":
              description: Successfully retrieved list of Category Values for the request
                provided
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/HearingChannels"
            "400":
              description: Bad Request
            "401":
              description: "Forbidden Error: Access denied"
            "500":
              description: Internal Server Error
          security:
            - Authorization: []
            - ServiceAuthorization: []
      "/refdata/commondata/lov/categories/{category-id}":
        get:
          tags:
            - crd-api-controller
          summary: CommonData API will be used to retrieve the list of category values for
            a given category id.
          description: "Any valid IDAM role should be able to access this API "
          operationId: retrieveHearingChannelByCategoryIdUsingGET_1
          parameters:
            - name: category-id
              in: path
              description: Any Valid String is allowed
              required: true
              schema:
                type: string
            - name: parent-category
              in: query
              description: Any Valid String is allowed
              required: false
              schema:
                type: string
            - name: parent-key
              in: query
              description: Any Valid String is allowed
              required: false
              schema:
                type: string
            - name: service-id
              in: query
              description: Any Valid String is allowed
              required: false
              schema:
                type: string
          responses:
            "200":
              description: Successfully retrieved list of Category Values for the request
                provided
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/HearingChannels"
            "400":
              description: Bad Request
            "401":
              description: "Forbidden Error: Access denied"
            "500":
              description: Internal Server Error
          security:
            - Authorization: []
            - ServiceAuthorization: []
    servers:
      - url: //rd-commondata-api-aat.service.core-compute-aat.internal/
    components:
      securitySchemes:
        Authorization:
          type: apiKey
          name: Authorization
          in: header
        ServiceAuthorization:
          type: apiKey
          name: ServiceAuthorization
          in: header
      schemas:
        CaseFlag:
          type: object
          properties:
            flags:
              type: array
              items:
                $ref: "#/components/schemas/Flag"
          title: CaseFlag
        Flag:
          type: object
          properties:
            FlagDetails:
              type: array
              items:
                $ref: "#/components/schemas/FlagDetail"
          title: Flag
        FlagDetail:
          type: object
          properties:
            Path:
              type: array
              items:
                type: string
            childFlags:
              type: array
              items:
                $ref: "#/components/schemas/FlagDetail"
            flagCode:
              type: string
            flagComment:
              type: boolean
            hearingRelevant:
              type: boolean
            isParent:
              type: boolean
            listOfValues:
              type: array
              items:
                $ref: "#/components/schemas/ListOfValue"
            listOfValuesLength:
              type: integer
              format: int32
            name:
              type: string
          title: FlagDetail
        HearingChannel:
          type: object
          properties:
            active_flag:
              type: boolean
            hint_text_cy:
              type: string
            hint_text_en:
              type: string
            key:
              type: string
            lov_order:
              type: integer
              format: int64
            parent_category:
              type: string
            parent_key:
              type: string
            value_cy:
              type: string
            value_en:
              type: string
          title: HearingChannel
        HearingChannels:
          type: object
          properties:
            list_of_values:
              type: array
              items:
                $ref: "#/components/schemas/HearingChannel"
          title: HearingChannels
        ListOfValue:
          type: object
          properties:
            key:
              type: string
            value:
              type: string
          title: ListOfValue