apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rd-judicial-api 
  description: rd-judicial-api API
spec:
  type: openapi
  system: rd-judicial-api
  lifecycle: production
  owner: dcd_group_referencedata_v2
  definition: |
    openapi: 3.0.0
    info:
      description: Api Documentation
      version: "1.0"
      title: Api Documentation
      termsOfService: urn:tos
      contact: {}
      license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0
    tags:
      - name: jrd-users-controller
        description: Jrd Users Controller
      - name: welcome-controller
        description: Welcome Controller
    paths:
      /:
        get:
          tags:
            - welcome-controller
          summary: Welcome message for the Judicial API
          operationId: welcomeUsingGET
          responses:
            "200":
              description: Welcome message
              content:
                application/json:
                  schema:
                    type: string
          deprecated: false
      /refdata/judicial/users:
        post:
          tags:
            - jrd-users-controller
          summary: This API to return judicial user profiles along with their active
            appointments and authorisations for the given request CCD Service Name
            or Objectid or SIDAMID
          description: |-
            **IDAM Roles to access API** :
             jrd-system-user,
             jrd-admin
          operationId: refreshUserProfileUsingPOST
          parameters:
            - name: page_number
              in: header
              description: page_number
              required: false
              schema:
                type: integer
                format: int32
            - name: page_size
              in: header
              description: page_size
              required: false
              schema:
                type: integer
                format: int32
            - name: sort_column
              in: header
              description: sort_column
              required: false
              schema:
                type: string
            - name: sort_direction
              in: header
              description: sort_direction
              required: false
              schema:
                type: string
          requestBody:
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/RefreshRoleRequest"
            description: refreshRoleRequest
            required: true
          responses:
            "200":
              description: The User profiles have been retrieved successfully
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/UserProfileRefreshResponse"
            "400":
              description: Bad Request
            "401":
              description: "Unauthorized Error : The requested resource is restricted and
                requires authentication"
            "403":
              description: "Forbidden Error: Access denied for invalid permissions"
            "404":
              description: The User Profile data could not be found
            "500":
              description: Internal Server Error
          security:
            - Authorization: []
            - ServiceAuthorization: []
          deprecated: false
      /refdata/judicial/users/fetch:
        post:
          tags:
            - jrd-users-controller
          summary: This API returns judicial user profiles with their appointments and
            authorisations
          description: |-
            **IDAM Roles to access API** :
             jrd-system-user,
             jrd-admin
          operationId: fetchUsersUsingPOST
          parameters:
            - name: page_number
              in: query
              description: page_number
              required: false
              schema:
                type: integer
                format: int32
            - name: page_size
              in: query
              description: page_size
              required: false
              schema:
                type: integer
                format: int32
          requestBody:
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/UserRequest"
            description: userRequest
            required: true
          responses:
            "200":
              description: Retrieve the set of judicial user profiles as per given request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/OrmResponse"
            "400":
              description: Bad Request
            "401":
              description: User Authentication Failed
            "403":
              description: Unauthorized
            "404":
              description: No Users Found
            "500":
              description: Internal Server Error
          security:
            - Authorization: []
            - ServiceAuthorization: []
          deprecated: false
      /refdata/judicial/users/search:
        post:
          tags:
            - jrd-users-controller
          summary: This endpoint will be used for user search based on partial query. When
            the consumers inputs any 3 characters, they will call this api to fetch
            the required result.
          description: "**Valid IDAM role is required to access this endpoint**"
          operationId: searchUsersUsingPOST
          requestBody:
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/UserSearchRequest"
            description: userSearchRequest
            required: true
          responses:
            "200":
              description: "Retrieve the user profiles for the given request. "
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/UserSearchResponse"
            "400":
              description: Bad Request
            "401":
              description: User Authentication Failed
            "403":
              description: Unauthorized
            "500":
              description: Internal Server Error
          security:
            - Authorization: []
            - ServiceAuthorization: []
          deprecated: false
    servers:
      - url: //rd-judicial-api-aat.service.core-compute-aat.internal/
    components:
      securitySchemes:
        Authorization:
          type: apiKey
          name: Authorization
          in: header
        ServiceAuthorization:
          type: apiKey
          name: ServiceAuthorization
          in: header
        UserEmail:
          type: apiKey
          name: UserEmail
          in: header
      schemas:
        AppointmentRefreshResponse:
          type: object
          properties:
            appointment:
              type: string
            appointment_type:
              type: string
            base_location_id:
              type: string
            cft_region:
              type: string
            cft_region_id:
              type: string
            court_name:
              type: string
            end_date:
              type: string
            epimms_id:
              type: string
            is_principal_appointment:
              type: string
            location:
              type: string
            location_id:
              type: string
            roles:
              type: array
              items:
                type: string
            service_code:
              type: string
            start_date:
              type: string
          title: AppointmentRefreshResponse
        AppointmentResponse:
          type: object
          properties:
            appointmentId:
              type: string
            baseLocationId:
              type: string
            contractTypeDescEn:
              type: string
            contractTypeId:
              type: string
            endDate:
              type: string
            isPrincipalAppointment:
              type: string
            regionDescEn:
              type: string
            regionId:
              type: string
            roleDescEn:
              type: string
            roleId:
              type: string
            startDate:
              type: string
          title: AppointmentResponse
        AuthorisationRefreshResponse:
          type: object
          properties:
            end_date:
              type: string
            jurisdiction:
              type: string
            service_code:
              type: string
            start_date:
              type: string
            ticket_code:
              type: string
            ticket_description:
              type: string
          title: AuthorisationRefreshResponse
        AuthorisationResponse:
          type: object
          properties:
            authorisationId:
              type: string
            jurisdiction:
              type: string
          title: AuthorisationResponse
        OrmResponse:
          type: object
          properties:
            appointments:
              type: array
              items:
                $ref: "#/components/schemas/AppointmentResponse"
            authorisations:
              type: array
              items:
                $ref: "#/components/schemas/AuthorisationResponse"
            idamId:
              type: string
          title: OrmResponse
        RefreshRoleRequest:
          type: object
          properties:
            ccdServiceName:
              type: string
            object_ids:
              type: array
              items:
                type: string
            sidam_ids:
              type: array
              items:
                type: string
          title: RefreshRoleRequest
        UserProfileRefreshResponse:
          type: object
          properties:
            appointments:
              type: array
              items:
                $ref: "#/components/schemas/AppointmentRefreshResponse"
            authorisations:
              type: array
              items:
                $ref: "#/components/schemas/AuthorisationRefreshResponse"
            email_id:
              type: string
            full_name:
              type: string
            known_as:
              type: string
            object_id:
              type: string
            post_nominals:
              type: string
            sidam_id:
              type: string
            surname:
              type: string
          title: UserProfileRefreshResponse
        UserRequest:
          type: object
          properties:
            userIds:
              type: array
              items:
                type: string
          title: UserRequest
        UserSearchRequest:
          type: object
          properties:
            location:
              type: string
            searchString:
              type: string
            serviceCode:
              type: string
          title: UserSearchRequest
        UserSearchResponse:
          type: object
          properties:
            emailId:
              type: string
            fullName:
              type: string
            idamId:
              type: string
            knownAs:
              type: string
            surname:
              type: string
            title:
              type: string
          title: UserSearchResponse