name: Diff CCD definition

on:
  pull_request:
    branches:
      - master

jobs:

  updateImages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install playwright
      - run: node docs/c4/generate.js

      - run: docker run --rm -d -p 8080:8080 -v $PWD:/usr/local/structurizr -e STRUCTURIZR_WORKSPACE_PATH=nfdiv structurizr/lite
        working-directory: docs/c4

      - run: |
          node export.js http://localhost:8080/ png
          mv *.png ./nfdiv/images
          docker stop $(docker ps -a -q)
        working-directory: docs/c4

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated images
          file_pattern: "*.png *.mdsl"

